export const GET_BIKES = 'bikes/GET_BIKES'
export const GET_BIKES_PENDING = GET_BIKES + '_PENDING'
export const GET_BIKES_FULFILLED = GET_BIKES + '_FULFILLED'
export const GET_BIKES_REJECTED = GET_BIKES + '_REJECTED'

export const GET_TRIPS = 'bikes/GET_TRIPS'
export const GET_TRIPS_PENDING = GET_TRIPS + '_PENDING'
export const GET_TRIPS_FULFILLED = GET_TRIPS + '_FULFILLED'
export const GET_TRIPS_REJECTED = GET_TRIPS + '_REJECTED'

export const REQUEST_BIKE = 'bikes/REQUEST_BIKE'
export const REQUEST_BIKE_PENDING = REQUEST_BIKE + '_PENDING'
export const REQUEST_BIKE_FULFILLED = REQUEST_BIKE + '_FULFILLED'
export const REQUEST_BIKE_REJECTED = REQUEST_BIKE + '_REJECTED'

export const RETURN_BIKE = 'bikes/RETURN_BIKE'
export const RETURN_BIKE_PENDING = RETURN_BIKE + '_PENDING'
export const RETURN_BIKE_FULFILLED = RETURN_BIKE + '_FULFILLED'
export const RETURN_BIKE_REJECTED = RETURN_BIKE + '_REJECTED'

export const SAVE_TRIP = 'bikes/SAVE_TRIP'
