export const GET_INFO = 'user/GET_INFO'
export const GET_INFO_PENDING = GET_INFO + '_PENDING'
export const GET_INFO_FULFILLED = GET_INFO + '_FULFILLED'
export const GET_INFO_REJECTED = GET_INFO + '_REJECTED'

export const REQUEST_UNLOCK = 'user/REQUEST_UNLOCK'
export const REQUEST_UNLOCK_PENDING = REQUEST_UNLOCK + '_PENDING'
export const REQUEST_UNLOCK_FULFILLED = REQUEST_UNLOCK + '_FULFILLED'
export const REQUEST_UNLOCK_REJECTED = REQUEST_UNLOCK + '_REJECTED'

export const REQUEST_LOCK = 'user/REQUEST_LOCK'
export const REQUEST_LOCK_PENDING = REQUEST_LOCK + '_PENDING'
export const REQUEST_LOCK_FULFILLED = REQUEST_LOCK + '_FULFILLED'
export const REQUEST_LOCK_REJECTED = REQUEST_LOCK + '_REJECTED'
