export const GET_USER = 'user/GET_USER'
export const GET_USER_PENDING = GET_USER + '_PENDING'
export const GET_USER_FULFILLED = GET_USER + '_FULFILLED'
export const GET_USER_REJECTED = GET_USER + '_REJECTED'

export const CHECK_CONFIRMATION = 'user/CHECK_CONFIRMATION'
export const CHECK_CONFIRMATION_PENDING = CHECK_CONFIRMATION + '_PENDING'
export const CHECK_CONFIRMATION_FULFILLED = CHECK_CONFIRMATION + '_FULFILLED'
export const CHECK_CONFIRMATION_REJECTED = CHECK_CONFIRMATION + '_REJECTED'

export const LOGIN = 'user/LOGIN'
export const LOGIN_PENDING = LOGIN + '_PENDING'
export const LOGIN_FULFILLED = LOGIN + '_FULFILLED'
export const LOGIN_REJECTED = LOGIN + '_REJECTED'

export const SIGNUP = 'user/SIGNUP'
export const SIGNUP_PENDING = SIGNUP + '_PENDING'
export const SIGNUP_FULFILLED = SIGNUP + '_FULFILLED'
export const SIGNUP_REJECTED = SIGNUP + '_REJECTED'

export const UPDATE = 'user/UPDATE'
export const UPDATE_PENDING = UPDATE + '_PENDING'
export const UPDATE_FULFILLED = UPDATE + '_FULFILLED'
export const UPDATE_REJECTED = UPDATE + '_REJECTED'

export const DELETE = 'user/DELETE'
export const DELETE_PENDING = DELETE + '_PENDING'
export const DELETE_FULFILLED = DELETE + '_FULFILLED'
export const DELETE_REJECTED = DELETE + '_REJECTED'

export const LOGOUT = 'user/LOGOUT'
